# docker-compose.yml
version: "3"
services:
  mongo:
    image: mongo
    restart: always
    ports:
    - 27017:27017
    environment:
     MONGO_INITDB_ROOT_USERNAME: devroot
     MONGO_INITDB_ROOT_PASSWORD: devpassword
  web:
      build: ./ExoCortex.Web/
      image: exocortex:dev
      depends_on:
      - mongo
      links:
      - mongo
      ports:
      - 8080:80
      environment:
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: "http://*:80"
        MongoCS: "mongodb://devroot:devpassword@mongo:27017"
        MongoDB: "ExoCortex"
        APIKey: "topsecret"